# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/diman/Рабочий стол/New Folder/untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(419, 210)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(290, 170, 121, 34))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 60, 111, 21))
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 90, 421, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 15, 421, 51))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(360, 60, 51, 21))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 121, 171, 20))
        self.label_2.setObjectName("label_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(0, 145, 421, 31))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.button_144p = QtWidgets.QPushButton(self.centralwidget)
        self.button_144p.setGeometry(QtCore.QRect(170, 110, 51, 41))
        self.button_144p.setObjectName("button_144p")
        self.button_360p = QtWidgets.QPushButton(self.centralwidget)
        self.button_360p.setGeometry(QtCore.QRect(230, 110, 51, 41))
        self.button_360p.setObjectName("button_360p")
        self.button_720p = QtWidgets.QPushButton(self.centralwidget)
        self.button_720p.setGeometry(QtCore.QRect(290, 110, 51, 41))
        self.button_720p.setObjectName("button_720p")
        self.button_audio = QtWidgets.QPushButton(self.centralwidget)
        self.button_audio.setGeometry(QtCore.QRect(350, 110, 51, 21))
        self.button_audio.setObjectName("button_audio")
        self.button_audio_2 = QtWidgets.QPushButton(self.centralwidget)
        self.button_audio_2.setGeometry(QtCore.QRect(350, 130, 51, 21))
        self.button_audio_2.setObjectName("button_audio_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(110, 60, 241, 21))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(0, 0, 111, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Загрузить"))
        self.label.setText(_translate("MainWindow", "Укажите ссылку :"))
        self.pushButton_2.setText(_translate("MainWindow", "OK"))
        self.label_2.setText(_translate("MainWindow", "Выберите формат видео :"))
        self.button_144p.setText(_translate("MainWindow", "144 p"))
        self.button_360p.setText(_translate("MainWindow", "360 p"))
        self.button_720p.setText(_translate("MainWindow", "720 p"))
        self.button_audio.setText(_translate("MainWindow", "Audio"))
        self.button_audio_2.setText(_translate("MainWindow", "Awt"))
        self.pushButton_3.setText(_translate("MainWindow", "Укажите папку"))
